/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as CommunityCollegeIdRouteImport } from './routes/community.$collegeId'
import { Route as CollegesIdRouteImport } from './routes/colleges.$id'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/colleges/',
  path: '/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCollegeIdRoute = CommunityCollegeIdRouteImport.update({
  id: '/community/$collegeId',
  path: '/community/$collegeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/colleges/$id',
  path: '/colleges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/admin': typeof AdminIndexRoute
  '/colleges': typeof CollegesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/report': typeof ReportRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/colleges/': typeof CollegesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/report'
    | '/admin/dashboard'
    | '/admin/login'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/admin/'
    | '/colleges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/report'
    | '/admin/dashboard'
    | '/admin/login'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/admin'
    | '/colleges'
  id:
    | '__root__'
    | '/'
    | '/report'
    | '/admin/dashboard'
    | '/admin/login'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/admin/'
    | '/colleges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReportRoute: typeof ReportRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CollegesIdRoute: typeof CollegesIdRoute
  CommunityCollegeIdRoute: typeof CommunityCollegeIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/colleges'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$collegeId': {
      id: '/community/$collegeId'
      path: '/community/$collegeId'
      fullPath: '/community/$collegeId'
      preLoaderRoute: typeof CommunityCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$id': {
      id: '/colleges/$id'
      path: '/colleges/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReportRoute: ReportRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  CollegesIdRoute: CollegesIdRoute,
  CommunityCollegeIdRoute: CommunityCollegeIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollegesIndexRoute: CollegesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
