/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupProjectsRouteImport } from './routes/setup-projects'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as CollegesIndexRouteImport } from './routes/colleges.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as CommunityCollegeIdRouteImport } from './routes/community.$collegeId'
import { Route as CollegesIdRouteImport } from './routes/colleges.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminPollsRouteImport } from './routes/admin.polls'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminIncidentsRouteImport } from './routes/admin.incidents'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminFeaturesRouteImport } from './routes/admin.features'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCommunityRouteImport } from './routes/admin.community'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminCollegesRouteImport } from './routes/admin.colleges'
import { Route as AdminCollaborateRouteImport } from './routes/admin.collaborate'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAdsRouteImport } from './routes/admin.ads'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupProjectsRoute = SetupProjectsRouteImport.update({
  id: '/setup-projects',
  path: '/setup-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/colleges/',
  path: '/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityCollegeIdRoute = CommunityCollegeIdRouteImport.update({
  id: '/community/$collegeId',
  path: '/community/$collegeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIdRoute = CollegesIdRouteImport.update({
  id: '/colleges/$id',
  path: '/colleges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPollsRoute = AdminPollsRouteImport.update({
  id: '/admin/polls',
  path: '/admin/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIncidentsRoute = AdminIncidentsRouteImport.update({
  id: '/admin/incidents',
  path: '/admin/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFeaturesRoute = AdminFeaturesRouteImport.update({
  id: '/admin/features',
  path: '/admin/features',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/admin/community',
  path: '/admin/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/admin/comments',
  path: '/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollegesRoute = AdminCollegesRouteImport.update({
  id: '/admin/colleges',
  path: '/admin/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollaborateRoute = AdminCollaborateRouteImport.update({
  id: '/admin/collaborate',
  path: '/admin/collaborate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/admin/ai',
  path: '/admin/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdsRoute = AdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup-projects': typeof SetupProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collaborate': typeof AdminCollaborateRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/colleges/': typeof CollegesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup-projects': typeof SetupProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collaborate': typeof AdminCollaborateRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/admin': typeof AdminIndexRoute
  '/colleges': typeof CollegesIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/messages': typeof MessagesRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/setup-projects': typeof SetupProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/trust': typeof TrustRoute
  '/admin/ads': typeof AdminAdsRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collaborate': typeof AdminCollaborateRoute
  '/admin/colleges': typeof AdminCollegesRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/features': typeof AdminFeaturesRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/incidents': typeof AdminIncidentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/polls': typeof AdminPollsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/users': typeof AdminUsersRoute
  '/colleges/$id': typeof CollegesIdRoute
  '/community/$collegeId': typeof CommunityCollegeIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/new': typeof ProjectsNewRoute
  '/admin/': typeof AdminIndexRoute
  '/colleges/': typeof CollegesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/global'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/setup-projects'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/collaborate'
    | '/admin/colleges'
    | '/admin/comments'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/features'
    | '/admin/feedback'
    | '/admin/incidents'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/polls'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/users'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/projects/$id'
    | '/projects/new'
    | '/admin/'
    | '/colleges/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/global'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/setup-projects'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/collaborate'
    | '/admin/colleges'
    | '/admin/comments'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/features'
    | '/admin/feedback'
    | '/admin/incidents'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/polls'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/users'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/projects/$id'
    | '/projects/new'
    | '/admin'
    | '/colleges'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/global'
    | '/messages'
    | '/privacy'
    | '/profile'
    | '/report'
    | '/setup-projects'
    | '/sitemap.xml'
    | '/terms'
    | '/trust'
    | '/admin/ads'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/collaborate'
    | '/admin/colleges'
    | '/admin/comments'
    | '/admin/community'
    | '/admin/dashboard'
    | '/admin/features'
    | '/admin/feedback'
    | '/admin/incidents'
    | '/admin/login'
    | '/admin/moderation'
    | '/admin/polls'
    | '/admin/posts'
    | '/admin/profile'
    | '/admin/users'
    | '/colleges/$id'
    | '/community/$collegeId'
    | '/projects/$id'
    | '/projects/new'
    | '/admin/'
    | '/colleges/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobalRoute: typeof GlobalRoute
  MessagesRoute: typeof MessagesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  SetupProjectsRoute: typeof SetupProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrustRoute: typeof TrustRoute
  AdminAdsRoute: typeof AdminAdsRoute
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCollaborateRoute: typeof AdminCollaborateRoute
  AdminCollegesRoute: typeof AdminCollegesRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFeaturesRoute: typeof AdminFeaturesRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminIncidentsRoute: typeof AdminIncidentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPollsRoute: typeof AdminPollsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CollegesIdRoute: typeof CollegesIdRoute
  CommunityCollegeIdRoute: typeof CommunityCollegeIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup-projects': {
      id: '/setup-projects'
      path: '/setup-projects'
      fullPath: '/setup-projects'
      preLoaderRoute: typeof SetupProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/colleges'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$collegeId': {
      id: '/community/$collegeId'
      path: '/community/$collegeId'
      fullPath: '/community/$collegeId'
      preLoaderRoute: typeof CommunityCollegeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$id': {
      id: '/colleges/$id'
      path: '/colleges/$id'
      fullPath: '/colleges/$id'
      preLoaderRoute: typeof CollegesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/polls': {
      id: '/admin/polls'
      path: '/admin/polls'
      fullPath: '/admin/polls'
      preLoaderRoute: typeof AdminPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/incidents': {
      id: '/admin/incidents'
      path: '/admin/incidents'
      fullPath: '/admin/incidents'
      preLoaderRoute: typeof AdminIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/features': {
      id: '/admin/features'
      path: '/admin/features'
      fullPath: '/admin/features'
      preLoaderRoute: typeof AdminFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/admin/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/colleges': {
      id: '/admin/colleges'
      path: '/admin/colleges'
      fullPath: '/admin/colleges'
      preLoaderRoute: typeof AdminCollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collaborate': {
      id: '/admin/collaborate'
      path: '/admin/collaborate'
      fullPath: '/admin/collaborate'
      preLoaderRoute: typeof AdminCollaborateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/admin/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ads': {
      id: '/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AdminAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobalRoute: GlobalRoute,
  MessagesRoute: MessagesRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  SetupProjectsRoute: SetupProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrustRoute: TrustRoute,
  AdminAdsRoute: AdminAdsRoute,
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCollaborateRoute: AdminCollaborateRoute,
  AdminCollegesRoute: AdminCollegesRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFeaturesRoute: AdminFeaturesRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminIncidentsRoute: AdminIncidentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPollsRoute: AdminPollsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminUsersRoute: AdminUsersRoute,
  CollegesIdRoute: CollegesIdRoute,
  CommunityCollegeIdRoute: CommunityCollegeIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollegesIndexRoute: CollegesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
